<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!-- CA2007 (ConfigureAwait) conflicts with xUnit1030 in test code; suppress globally for test projects -->
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing"/>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="xunit.v3"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Aspires\Dst.Aspires.AppHost\Dst.Aspires.AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Aspire.Hosting.ApplicationModel" />
    <Using Include="Aspire.Hosting.Testing" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
