<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\..\Aspires\Dst.Aspires.ServiceDefaults\Dst.Aspires.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Dst.Core\Dst.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.Orleans.Client" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" />
    <PackageReference Include="Aspire.StackExchange.Redis" />
  </ItemGroup>
</Project>
