<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Apps\Dst.Apps.OrleansSiloWebApp\Dst.Apps.OrleansSiloWebApp.csproj" />
    <ProjectReference Include="..\..\Apps\Dst.Apps.OrleansClientWebApp\Dst.Apps.OrleansClientWebApp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Orleans" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>
</Project>
