<Project Sdk="Aspire.AppHost.Sdk/13.5.3">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\OrleansSilo\Dst.OrleansSilo.WebApp\Dst.OrleansSilo.WebApp.csproj" />
    <ProjectReference Include="..\..\Dst.WebApiApp\Dst.WebApiApp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Orleans" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>
</Project>
